// Code generated by go-swagger; DO NOT EDIT.

package files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Skewax/backend/pkg/swagger/server/models"
)

// GetReadFileOKCode is the HTTP code returned for type GetReadFileOK
const GetReadFileOKCode int = 200

/*
GetReadFileOK OK: returns full data on file

swagger:response getReadFileOK
*/
type GetReadFileOK struct {

	/*
	  In: Body
	*/
	Payload *models.FileDataResponse `json:"body,omitempty"`
}

// NewGetReadFileOK creates GetReadFileOK with default headers values
func NewGetReadFileOK() *GetReadFileOK {

	return &GetReadFileOK{}
}

// WithPayload adds the payload to the get read file o k response
func (o *GetReadFileOK) WithPayload(payload *models.FileDataResponse) *GetReadFileOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get read file o k response
func (o *GetReadFileOK) SetPayload(payload *models.FileDataResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReadFileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetReadFileUnauthorizedCode is the HTTP code returned for type GetReadFileUnauthorized
const GetReadFileUnauthorizedCode int = 401

/*
GetReadFileUnauthorized malformed/incorrect session token

swagger:response getReadFileUnauthorized
*/
type GetReadFileUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.BasicResponse `json:"body,omitempty"`
}

// NewGetReadFileUnauthorized creates GetReadFileUnauthorized with default headers values
func NewGetReadFileUnauthorized() *GetReadFileUnauthorized {

	return &GetReadFileUnauthorized{}
}

// WithPayload adds the payload to the get read file unauthorized response
func (o *GetReadFileUnauthorized) WithPayload(payload *models.BasicResponse) *GetReadFileUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get read file unauthorized response
func (o *GetReadFileUnauthorized) SetPayload(payload *models.BasicResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReadFileUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetReadFileInternalServerErrorCode is the HTTP code returned for type GetReadFileInternalServerError
const GetReadFileInternalServerErrorCode int = 500

/*
GetReadFileInternalServerError generic server error

swagger:response getReadFileInternalServerError
*/
type GetReadFileInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.BasicResponse `json:"body,omitempty"`
}

// NewGetReadFileInternalServerError creates GetReadFileInternalServerError with default headers values
func NewGetReadFileInternalServerError() *GetReadFileInternalServerError {

	return &GetReadFileInternalServerError{}
}

// WithPayload adds the payload to the get read file internal server error response
func (o *GetReadFileInternalServerError) WithPayload(payload *models.BasicResponse) *GetReadFileInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get read file internal server error response
func (o *GetReadFileInternalServerError) SetPayload(payload *models.BasicResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReadFileInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
