// Code generated by go-swagger; DO NOT EDIT.

package files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Skewax/backend/pkg/swagger/server/models"
)

// GetGetFilesOKCode is the HTTP code returned for type GetGetFilesOK
const GetGetFilesOKCode int = 200

/*
GetGetFilesOK OK: a list of all users files

swagger:response getGetFilesOK
*/
type GetGetFilesOK struct {

	/*
	  In: Body
	*/
	Payload *GetGetFilesOKBody `json:"body,omitempty"`
}

// NewGetGetFilesOK creates GetGetFilesOK with default headers values
func NewGetGetFilesOK() *GetGetFilesOK {

	return &GetGetFilesOK{}
}

// WithPayload adds the payload to the get get files o k response
func (o *GetGetFilesOK) WithPayload(payload *GetGetFilesOKBody) *GetGetFilesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get get files o k response
func (o *GetGetFilesOK) SetPayload(payload *GetGetFilesOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGetFilesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetGetFilesUnauthorizedCode is the HTTP code returned for type GetGetFilesUnauthorized
const GetGetFilesUnauthorizedCode int = 401

/*
GetGetFilesUnauthorized malformed/incorrect session token

swagger:response getGetFilesUnauthorized
*/
type GetGetFilesUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.BasicResponse `json:"body,omitempty"`
}

// NewGetGetFilesUnauthorized creates GetGetFilesUnauthorized with default headers values
func NewGetGetFilesUnauthorized() *GetGetFilesUnauthorized {

	return &GetGetFilesUnauthorized{}
}

// WithPayload adds the payload to the get get files unauthorized response
func (o *GetGetFilesUnauthorized) WithPayload(payload *models.BasicResponse) *GetGetFilesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get get files unauthorized response
func (o *GetGetFilesUnauthorized) SetPayload(payload *models.BasicResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGetFilesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetGetFilesInternalServerErrorCode is the HTTP code returned for type GetGetFilesInternalServerError
const GetGetFilesInternalServerErrorCode int = 500

/*
GetGetFilesInternalServerError generic server error

swagger:response getGetFilesInternalServerError
*/
type GetGetFilesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.BasicResponse `json:"body,omitempty"`
}

// NewGetGetFilesInternalServerError creates GetGetFilesInternalServerError with default headers values
func NewGetGetFilesInternalServerError() *GetGetFilesInternalServerError {

	return &GetGetFilesInternalServerError{}
}

// WithPayload adds the payload to the get get files internal server error response
func (o *GetGetFilesInternalServerError) WithPayload(payload *models.BasicResponse) *GetGetFilesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get get files internal server error response
func (o *GetGetFilesInternalServerError) SetPayload(payload *models.BasicResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGetFilesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
