// Code generated by go-swagger; DO NOT EDIT.

package files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostUpdateFileHandlerFunc turns a function with the right signature into a post update file handler
type PostUpdateFileHandlerFunc func(PostUpdateFileParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostUpdateFileHandlerFunc) Handle(params PostUpdateFileParams) middleware.Responder {
	return fn(params)
}

// PostUpdateFileHandler interface for that can handle valid post update file params
type PostUpdateFileHandler interface {
	Handle(PostUpdateFileParams) middleware.Responder
}

// NewPostUpdateFile creates a new http.Handler for the post update file operation
func NewPostUpdateFile(ctx *middleware.Context, handler PostUpdateFileHandler) *PostUpdateFile {
	return &PostUpdateFile{Context: ctx, Handler: handler}
}

/*
	PostUpdateFile swagger:route POST /updateFile Files postUpdateFile

set the text of a file by ID
*/
type PostUpdateFile struct {
	Context *middleware.Context
	Handler PostUpdateFileHandler
}

func (o *PostUpdateFile) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostUpdateFileParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostUpdateFileBody post update file body
//
// swagger:model PostUpdateFileBody
type PostUpdateFileBody struct {

	// file id
	// Required: true
	FileID *string `json:"file_id"`

	// name
	Name string `json:"name,omitempty"`

	// session token
	// Required: true
	SessionToken *string `json:"session_token"`

	// text
	Text string `json:"text,omitempty"`

	// user id
	// Required: true
	UserID *string `json:"user_id"`
}

// Validate validates this post update file body
func (o *PostUpdateFileBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateFileID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateSessionToken(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateUserID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostUpdateFileBody) validateFileID(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"file_id", "body", o.FileID); err != nil {
		return err
	}

	return nil
}

func (o *PostUpdateFileBody) validateSessionToken(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"session_token", "body", o.SessionToken); err != nil {
		return err
	}

	return nil
}

func (o *PostUpdateFileBody) validateUserID(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"user_id", "body", o.UserID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post update file body based on context it is used
func (o *PostUpdateFileBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostUpdateFileBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostUpdateFileBody) UnmarshalBinary(b []byte) error {
	var res PostUpdateFileBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
