version: "3"

tasks:
  build:
    desc: build the app
    cmds:
    - GOFLAGS=-mod=mod go build -o bin/skewax-backend internal/main.go

  run:
    desc: run the app
    cmds:
    - GOFLAGS=-mod=mod go run internal/main.go

  swagger.gen:
    desc: generate swagger code
    cmds:
    - GOFLAGS=-mod=mod go generate github.com/Skewax/backend/internal github.com/Skewax/backend/pkg/swagger


  swagger.validate:
    desc: Validate Swagger Code
    cmds:
    - swagger validate pkg/swagger/swagger.yml

  swagger.doc:
    desc: generate docs for swagger
    cmds:
    - docker run --rm -i yousan/swagger-yaml-to-html < pkg/swagger/swagger.yml > docs/index.html

