// Code generated by go-swagger; DO NOT EDIT.

package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Skewax/backend/pkg/swagger/server/models"
)

// PostLogoutOKCode is the HTTP code returned for type PostLogoutOK
const PostLogoutOKCode int = 200

/*
PostLogoutOK OK

swagger:response postLogoutOK
*/
type PostLogoutOK struct {

	/*
	  In: Body
	*/
	Payload *models.BasicResponse `json:"body,omitempty"`
}

// NewPostLogoutOK creates PostLogoutOK with default headers values
func NewPostLogoutOK() *PostLogoutOK {

	return &PostLogoutOK{}
}

// WithPayload adds the payload to the post logout o k response
func (o *PostLogoutOK) WithPayload(payload *models.BasicResponse) *PostLogoutOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post logout o k response
func (o *PostLogoutOK) SetPayload(payload *models.BasicResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostLogoutOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostLogoutBadRequestCode is the HTTP code returned for type PostLogoutBadRequest
const PostLogoutBadRequestCode int = 400

/*
PostLogoutBadRequest malformed or nonexistent session token

swagger:response postLogoutBadRequest
*/
type PostLogoutBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.BasicResponse `json:"body,omitempty"`
}

// NewPostLogoutBadRequest creates PostLogoutBadRequest with default headers values
func NewPostLogoutBadRequest() *PostLogoutBadRequest {

	return &PostLogoutBadRequest{}
}

// WithPayload adds the payload to the post logout bad request response
func (o *PostLogoutBadRequest) WithPayload(payload *models.BasicResponse) *PostLogoutBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post logout bad request response
func (o *PostLogoutBadRequest) SetPayload(payload *models.BasicResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostLogoutBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostLogoutInternalServerErrorCode is the HTTP code returned for type PostLogoutInternalServerError
const PostLogoutInternalServerErrorCode int = 500

/*
PostLogoutInternalServerError generic server error

swagger:response postLogoutInternalServerError
*/
type PostLogoutInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.BasicResponse `json:"body,omitempty"`
}

// NewPostLogoutInternalServerError creates PostLogoutInternalServerError with default headers values
func NewPostLogoutInternalServerError() *PostLogoutInternalServerError {

	return &PostLogoutInternalServerError{}
}

// WithPayload adds the payload to the post logout internal server error response
func (o *PostLogoutInternalServerError) WithPayload(payload *models.BasicResponse) *PostLogoutInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post logout internal server error response
func (o *PostLogoutInternalServerError) SetPayload(payload *models.BasicResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostLogoutInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
