// Code generated by go-swagger; DO NOT EDIT.

package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostLogoutHandlerFunc turns a function with the right signature into a post logout handler
type PostLogoutHandlerFunc func(PostLogoutParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostLogoutHandlerFunc) Handle(params PostLogoutParams) middleware.Responder {
	return fn(params)
}

// PostLogoutHandler interface for that can handle valid post logout params
type PostLogoutHandler interface {
	Handle(PostLogoutParams) middleware.Responder
}

// NewPostLogout creates a new http.Handler for the post logout operation
func NewPostLogout(ctx *middleware.Context, handler PostLogoutHandler) *PostLogout {
	return &PostLogout{Context: ctx, Handler: handler}
}

/*
	PostLogout swagger:route POST /logout Authentication postLogout

removes the current session token from the database
*/
type PostLogout struct {
	Context *middleware.Context
	Handler PostLogoutHandler
}

func (o *PostLogout) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostLogoutParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostLogoutBody post logout body
//
// swagger:model PostLogoutBody
type PostLogoutBody struct {

	// token
	Token string `json:"token,omitempty"`

	// user id
	// Required: true
	UserID *string `json:"user_id"`
}

// Validate validates this post logout body
func (o *PostLogoutBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateUserID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostLogoutBody) validateUserID(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"user_id", "body", o.UserID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post logout body based on context it is used
func (o *PostLogoutBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostLogoutBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostLogoutBody) UnmarshalBinary(b []byte) error {
	var res PostLogoutBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
