// Code generated by go-swagger; DO NOT EDIT.

// Package restapi skewax-backend
//
//	Skewax backend server to interface with google drive
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 0.3.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
