// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/Skewax/backend/pkg/swagger/server/restapi/operations/authentication"
	"github.com/Skewax/backend/pkg/swagger/server/restapi/operations/files"
)

// NewSkewaxBackendAPI creates a new SkewaxBackend instance
func NewSkewaxBackendAPI(spec *loads.Document) *SkewaxBackendAPI {
	return &SkewaxBackendAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		FilesGetGetFilesHandler: files.GetGetFilesHandlerFunc(func(params files.GetGetFilesParams) middleware.Responder {
			return middleware.NotImplemented("operation files.GetGetFiles has not yet been implemented")
		}),
		FilesGetReadFileHandler: files.GetReadFileHandlerFunc(func(params files.GetReadFileParams) middleware.Responder {
			return middleware.NotImplemented("operation files.GetReadFile has not yet been implemented")
		}),
		AuthenticationGetTokenLoginHandler: authentication.GetTokenLoginHandlerFunc(func(params authentication.GetTokenLoginParams) middleware.Responder {
			return middleware.NotImplemented("operation authentication.GetTokenLogin has not yet been implemented")
		}),
		FilesPostCreateFileHandler: files.PostCreateFileHandlerFunc(func(params files.PostCreateFileParams) middleware.Responder {
			return middleware.NotImplemented("operation files.PostCreateFile has not yet been implemented")
		}),
		FilesPostDeleteFileHandler: files.PostDeleteFileHandlerFunc(func(params files.PostDeleteFileParams) middleware.Responder {
			return middleware.NotImplemented("operation files.PostDeleteFile has not yet been implemented")
		}),
		AuthenticationPostLogoutHandler: authentication.PostLogoutHandlerFunc(func(params authentication.PostLogoutParams) middleware.Responder {
			return middleware.NotImplemented("operation authentication.PostLogout has not yet been implemented")
		}),
		AuthenticationPostNewLoginHandler: authentication.PostNewLoginHandlerFunc(func(params authentication.PostNewLoginParams) middleware.Responder {
			return middleware.NotImplemented("operation authentication.PostNewLogin has not yet been implemented")
		}),
		FilesPostUpdateFileHandler: files.PostUpdateFileHandlerFunc(func(params files.PostUpdateFileParams) middleware.Responder {
			return middleware.NotImplemented("operation files.PostUpdateFile has not yet been implemented")
		}),
	}
}

/*SkewaxBackendAPI Skewax backend server to interface with google drive */
type SkewaxBackendAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// FilesGetGetFilesHandler sets the operation handler for the get get files operation
	FilesGetGetFilesHandler files.GetGetFilesHandler
	// FilesGetReadFileHandler sets the operation handler for the get read file operation
	FilesGetReadFileHandler files.GetReadFileHandler
	// AuthenticationGetTokenLoginHandler sets the operation handler for the get token login operation
	AuthenticationGetTokenLoginHandler authentication.GetTokenLoginHandler
	// FilesPostCreateFileHandler sets the operation handler for the post create file operation
	FilesPostCreateFileHandler files.PostCreateFileHandler
	// FilesPostDeleteFileHandler sets the operation handler for the post delete file operation
	FilesPostDeleteFileHandler files.PostDeleteFileHandler
	// AuthenticationPostLogoutHandler sets the operation handler for the post logout operation
	AuthenticationPostLogoutHandler authentication.PostLogoutHandler
	// AuthenticationPostNewLoginHandler sets the operation handler for the post new login operation
	AuthenticationPostNewLoginHandler authentication.PostNewLoginHandler
	// FilesPostUpdateFileHandler sets the operation handler for the post update file operation
	FilesPostUpdateFileHandler files.PostUpdateFileHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *SkewaxBackendAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *SkewaxBackendAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *SkewaxBackendAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *SkewaxBackendAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *SkewaxBackendAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *SkewaxBackendAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *SkewaxBackendAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *SkewaxBackendAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *SkewaxBackendAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the SkewaxBackendAPI
func (o *SkewaxBackendAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.FilesGetGetFilesHandler == nil {
		unregistered = append(unregistered, "files.GetGetFilesHandler")
	}
	if o.FilesGetReadFileHandler == nil {
		unregistered = append(unregistered, "files.GetReadFileHandler")
	}
	if o.AuthenticationGetTokenLoginHandler == nil {
		unregistered = append(unregistered, "authentication.GetTokenLoginHandler")
	}
	if o.FilesPostCreateFileHandler == nil {
		unregistered = append(unregistered, "files.PostCreateFileHandler")
	}
	if o.FilesPostDeleteFileHandler == nil {
		unregistered = append(unregistered, "files.PostDeleteFileHandler")
	}
	if o.AuthenticationPostLogoutHandler == nil {
		unregistered = append(unregistered, "authentication.PostLogoutHandler")
	}
	if o.AuthenticationPostNewLoginHandler == nil {
		unregistered = append(unregistered, "authentication.PostNewLoginHandler")
	}
	if o.FilesPostUpdateFileHandler == nil {
		unregistered = append(unregistered, "files.PostUpdateFileHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *SkewaxBackendAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *SkewaxBackendAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *SkewaxBackendAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *SkewaxBackendAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *SkewaxBackendAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *SkewaxBackendAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the skewax backend API
func (o *SkewaxBackendAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *SkewaxBackendAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/getFiles"] = files.NewGetGetFiles(o.context, o.FilesGetGetFilesHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/readFile"] = files.NewGetReadFile(o.context, o.FilesGetReadFileHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/tokenLogin"] = authentication.NewGetTokenLogin(o.context, o.AuthenticationGetTokenLoginHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/createFile"] = files.NewPostCreateFile(o.context, o.FilesPostCreateFileHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/deleteFile"] = files.NewPostDeleteFile(o.context, o.FilesPostDeleteFileHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/logout"] = authentication.NewPostLogout(o.context, o.AuthenticationPostLogoutHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/newLogin"] = authentication.NewPostNewLogin(o.context, o.AuthenticationPostNewLoginHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/updateFile"] = files.NewPostUpdateFile(o.context, o.FilesPostUpdateFileHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *SkewaxBackendAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *SkewaxBackendAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *SkewaxBackendAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *SkewaxBackendAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *SkewaxBackendAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
