consumes:
- application/json
info:
  description: Skewax backend server to interface with google drive
  title: skewax-backend
  version: 0.3.0
produces:
- application/json
schemes:
- http
# - https
swagger: "2.0"



definitions:
  User:
    type: object
    properties:
      name:
        type: string
      image:
        type: string
    required:
      - name
      - image
  BasicFileObject:
    type: object
    properties:
      name:
        type: string
      id:
        type: string
  FileDataResponse:
    properties:
      error:
        type: string
      text:
        type: string
      id:
        type: string
      modifiedTime:
        type: integer
        format: int64
      writable:
        description: if this file is meant to be read by skewax
        type: boolean
  BasicResponse:
    properties:
      error:
        type: string
  LoginResponse:
    properties:
      error:
        type: string
      session_token:
        type: string
      timeout:
        type: integer
        format: int64
      user:
        $ref: '#/definitions/User'
 


parameters:
  TokenAuth:
    description: simply sending along the session token for authentication
    in: body
    name: body
    required: true
    schema:
      type: object
      required:
      - session_token
      - user_id
      properties:
        user_id:
          type: string
        token:
          type: string
  FileReference:
    description: a reference to a specific file by ID and an authentication token with it
    in: body
    name: body
    required: true
    schema:
      type: object
      required:
      - session_token
      - user_id
      - file_id
      properties:
        session_token:
          type: string
        file_id:
          type: string
        user_id:
          type: string




paths:
  /newLogin:
    post:
      tags:
      - Authentication
      operationId: googleLogin
      summary: logs in a user from google auth state
      produces:
      - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - user
              - code
              - hosted_domain
              - prompt
              - scope
              - csrf_state
            properties:
              user:
                type: string
              code:
                type: string
              hosted_domain:
                type: string
              prompt:
                type: string
              scope:
                type: string
              csrf_state:
                type: string
      responses:
        200:
          description: OK
          schema:
            type: object
            $ref: '#/definitions/LoginResponse'
        400:
          description: an incorrect/incorrectly formatted ID
          schema:
            type: object
            $ref: '#/definitions/BasicResponse'
        401:
          description: user did not grant all needed scopes
          schema:
            type: object
            $ref: '#/definitions/BasicResponse'
        408:
          description: timeout of this ID
          schema:
            type: object
            $ref: '#/definitions/BasicResponse'
        500:
          description: generic server error
          schema:
            type: object
            $ref: '#/definitions/BasicResponse'
  /tokenLogin:
    get:
      tags:
      - Authentication
      operationId: tokenLogin
      summary: verifies a serssion token and returns user data. Will also generate a new session token and replace it
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/TokenAuth'
      responses:
        200:
          description: OK
          schema:
            type: object
            $ref: '#/definitions/LoginResponse'
        400:
          description: an incorrect/incorrectly formatted ID
          schema:
            type: object
            $ref: '#/definitions/BasicResponse'
        500:
          description: generic server error
          schema:
            type: object
            $ref: '#/definitions/BasicResponse'
  /logout:
    post:
      tags:
      - Authentication
      operationId: logout
      summary: removes the current session token from the database
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/TokenAuth'
      responses:
        200:
          description: OK
          schema:
            type: object
            $ref: '#/definitions/BasicResponse'
        400:
          description: malformed or nonexistent session token
          schema:
            type: object
            $ref: '#/definitions/BasicResponse'
        500:
          description: generic server error
          schema:
            type: object
            $ref: '#/definitions/BasicResponse'

  /getFiles:
    get:
      summary: get all files of user
      operationId: getFiles
      tags:
      - Files
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/TokenAuth'
      responses:
        200:
          description: "OK: a list of all users files"
          schema:
            type: object
            properties:
              error:
                type: string
              files:
                type: array
                items:
                  $ref: '#/definitions/BasicFileObject'
        401:
          description: malformed/incorrect session token
          schema:
            type: object
            $ref: '#/definitions/BasicResponse'
        500:
          description: generic server error
          schema:
            type: object
            $ref: '#/definitions/BasicResponse'
  /readFile:
    get:
      summary: get text and metadata of file by ID
      tags:
      - Files
      operationId: readFile
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/FileReference'
      responses:
        200:
          description: "OK: returns full data on file"
          schema:
            type: object
            $ref: '#/definitions/FileDataResponse'
        401:
          description: malformed/incorrect session token
          schema:
            type: object
            $ref: '#/definitions/BasicResponse'
        500:
          description: generic server error
          schema:
            type: object
            $ref: '#/definitions/BasicResponse'
  /updateFile:
    post:
      summary: set the text of a file by ID
      operationId: updateFile
      tags:
      - Files
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        schema:
          type: object
          required:
          - session_token
          - user_id
          - file_id
          properties:
            session_token:
              type: string
            user_id:
              type: string
            file_id: 
              type: string
            text:
              type: string
            name:
              type: string
      responses:
        200:
          description: "OK: updated file"
          schema:
            type: object
            $ref: '#/definitions/BasicResponse'
        400:
          description: malformed/incorrect session id
          schema:
            type: object
            $ref: '#/definitions/BasicResponse'
        500:
          description: internal server error
          schema:
            type: object
            $ref: '#/definitions/BasicResponse'
  /createFile:
    post:
      summary: create file with name and text, returns basic file object
      tags:
      - Files
      operationId: createFile
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        schema:
          type: object
          required:
          - session_token
          - user_id
          - file_name
          - text
          properties:
            session_token:
              type: string
            user_id:
              type: string
            file_name:
              type: string
            text:
              type: string
      responses:
        200:
          description: "OK: updated file"
          schema:
            type: object
            properties:
              error:
                type: string
              file:
                $ref: '#/definitions/BasicFileObject'
        400:
          description: malformed/invalid session token
          schema:
            type: object
            $ref: '#/definitions/BasicResponse'
        500:
          description: generic server error
          schema:
            type: object
            $ref: '#/definitions/BasicResponse'
  /deleteFile:
    post:
      summary: delete file by ID
      tags:
      - Files
      operationId: deleteFile
      produces:
      - application/json
      parameters:
      - $ref: '#/parameters/FileReference'
      responses:
        200:
          description: "OK: file deleted"
          schema:
            type: object
            $ref: '#/definitions/BasicResponse'
        400:
          description: malformed/invalid session token
          schema:
            type: object
            $ref: '#/definitions/BasicResponse'
        500:
          description: generic server error
          schema:
            type: object
            $ref: '#/definitions/BasicResponse'

