// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FileDataResponse file data response
//
// swagger:model FileDataResponse
type FileDataResponse struct {

	// error
	Error string `json:"error,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// modified time
	ModifiedTime int64 `json:"modifiedTime,omitempty"`

	// text
	Text string `json:"text,omitempty"`

	// if this file is meant to be read by skewax
	Writable bool `json:"writable,omitempty"`
}

// Validate validates this file data response
func (m *FileDataResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this file data response based on context it is used
func (m *FileDataResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FileDataResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FileDataResponse) UnmarshalBinary(b []byte) error {
	var res FileDataResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
